#!/usr/bin/env bash

# install.sh -- set up a physdemo suite: one Python environment shared
#   by every demonstration tool, one bin/ directory of tool commands,
#   and one activate.sh that puts both on the PATH.
#
# This script uses nothing specific to any one computer: plain bash, a
#   Python 3.10 or later, and pip. Cluster conveniences (an Lmod
#   modulefile, Slurm notes) live under extras/ and site/ and are
#   optional.
#
# Usage:
#   ./install.sh --prefix DIR [--venv DIR] [--python EXE]
#                [--no-packages] [--lmod-out FILE]
#
#   --prefix DIR     The suite root. Receives bin/ and activate.sh.
#                    Default: $HOME/physdemo
#   --venv DIR       The Python environment to use. If DIR does not
#                    exist it is created as a venv; if it exists (a venv
#                    or a conda environment prefix) it is ADOPTED as is.
#                    Default: PREFIX/venv
#   --python EXE     The interpreter that creates a new venv. Ignored
#                    when --venv names an existing environment.
#                    Default: python3
#   --no-packages    Do not pip-install requirements.txt. For adopting an
#                    environment that already holds the packages.
#   --lmod-out FILE  Also write an Lmod modulefile (Lua) to FILE, for
#                    sites that use environment modules.
#
# Several prefixes may share one environment: a "release" prefix whose
#   bin/ points at tagged checkouts for students and a "dev" prefix whose
#   bin/ points at an instructor's working copies, both given the same
#   --venv. After installing, add tools with install_tool.sh.

set -euo pipefail

# The directory holding this script, with symlinks resolved, found
#   without GNU-only tools so that it also works on macOS.
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"

prefix="$HOME/physdemo"
venv_dir=""
python_exe="python3"
install_packages=1
lmod_out=""

while [ $# -gt 0 ]; do
    case "$1" in
        --prefix)      prefix="$2"; shift 2 ;;
        --venv)        venv_dir="$2"; shift 2 ;;
        --python)      python_exe="$2"; shift 2 ;;
        --no-packages) install_packages=0; shift ;;
        --lmod-out)    lmod_out="$2"; shift 2 ;;
        -h|--help)     sed -n '3,33p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "install.sh: unknown argument: $1" >&2; exit 2 ;;
    esac
done

mkdir -p "$prefix/bin"
prefix="$(cd "$prefix" && pwd -P)"
[ -n "$venv_dir" ] || venv_dir="$prefix/venv"

# Create the environment, or adopt the one that is already there.
if [ -x "$venv_dir/bin/python" ] || [ -x "$venv_dir/bin/python3" ]; then
    echo "Adopting the existing environment at $venv_dir"
else
    echo "Creating a venv at $venv_dir with $python_exe"
    "$python_exe" -c 'import sys; sys.exit(sys.version_info < (3, 10))' \
        || { echo "install.sh: Python 3.10 or later is required" >&2
             exit 1; }
    "$python_exe" -m venv "$venv_dir"
fi
venv_dir="$(cd "$venv_dir" && pwd -P)"
env_python="$venv_dir/bin/python"
[ -x "$env_python" ] || env_python="$venv_dir/bin/python3"

if [ "$install_packages" -eq 1 ]; then
    echo "Installing the pinned packages (requirements.txt)"
    "$env_python" -m pip install --upgrade pip
    "$env_python" -m pip install -r "$script_dir/requirements.txt"
fi

# Write activate.sh. It does what a venv's own activate does -- set
#   VIRTUAL_ENV and prepend to PATH -- by hand, so that it works equally
#   for a venv and for an adopted conda prefix, and adds the suite bin/.
cat > "$prefix/activate.sh" <<ACTIVATE
# physdemo activate script. SOURCE this file from bash or zsh:
#     source $prefix/activate.sh
# It puts the suite's tools and its Python on the PATH. Undo it with:
#     physdemo_deactivate
# Generated by install.sh on $(date '+%Y-%m-%d'); do not edit by hand,
#   re-run install.sh instead.

physdemo_deactivate () {
    if [ -n "\${_PHYSDEMO_OLD_PATH:-}" ]; then
        PATH="\$_PHYSDEMO_OLD_PATH"; export PATH
        unset _PHYSDEMO_OLD_PATH
    fi
    if [ -n "\${_PHYSDEMO_OLD_PS1:-}" ]; then
        PS1="\$_PHYSDEMO_OLD_PS1"; export PS1
        unset _PHYSDEMO_OLD_PS1
    fi
    unset VIRTUAL_ENV PHYSDEMO_HOME
    hash -r 2>/dev/null || true
    unset -f physdemo_deactivate
}

# Re-sourcing must not stack PATH entries.
if [ -n "\${_PHYSDEMO_OLD_PATH:-}" ]; then
    PATH="\$_PHYSDEMO_OLD_PATH"
fi
_PHYSDEMO_OLD_PATH="\$PATH"
PHYSDEMO_HOME="$prefix"; export PHYSDEMO_HOME
VIRTUAL_ENV="$venv_dir"; export VIRTUAL_ENV
PATH="$prefix/bin:$venv_dir/bin:\$PATH"; export PATH
unset PYTHONHOME
if [ -z "\${PHYSDEMO_DISABLE_PROMPT:-}" ] && [ -n "\${PS1:-}" ]; then
    _PHYSDEMO_OLD_PS1="\$PS1"
    PS1="(physdemo) \$PS1"; export PS1
fi
hash -r 2>/dev/null || true
ACTIVATE

# The `physdemo` command: list the installed tools and the environment.
cat > "$prefix/bin/physdemo" <<'LISTER'
#!/usr/bin/env bash
# physdemo -- show what this suite provides. Generated by install.sh.
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
root="$(dirname "$here")"
echo "physdemo suite at $root"
echo "  python: $(command -v python3)  ($(python3 --version 2>&1))"
echo "  tools:"
if [ -s "$root/tools.list" ]; then
    sed 's/^/    /' "$root/tools.list"
else
    echo "    (none yet; add one with install_tool.sh)"
fi
LISTER
chmod +x "$prefix/bin/physdemo"
touch "$prefix/tools.list"

if [ -n "$lmod_out" ]; then
    mkdir -p "$(dirname "$lmod_out")"
    sed -e "s|@PREFIX@|$prefix|g" -e "s|@VENV@|$venv_dir|g" \
        "$script_dir/extras/lmod/physdemo.lua.in" > "$lmod_out"
    echo "Wrote the Lmod modulefile $lmod_out"
fi

echo
echo "Done. Next:"
echo "  $script_dir/install_tool.sh --prefix $prefix /path/to/a/tool"
echo "  source $prefix/activate.sh"
echo "A shell alias makes that one word, for example:"
echo "  alias sdemo='source $prefix/activate.sh'"
